//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_PERMISSION
    {
        public ACCOUNT_PERMISSION()
        {
            this.accounts = new HashSet<account>();
        }
    
        public decimal ID_ACCOUNT_PERMISSION { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
    }
}
