//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account() { }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account(String username, String password)
        {
            //this.comments = new HashSet<comment>();
            this.ID_ACCOUNT = new Random().Next();
            this.PASSWORD = password;
            this.USERNAME = username;
            this.ID_ACCOUNT_PERMISSIONS = 0;
        }
    
        public decimal ID_ACCOUNT { get; set; }
        public Nullable<decimal> ID_ACCOUNT_PERMISSIONS { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ACCOUNT_PERMISSION ACCOUNT_PERMISSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
