//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.comments = new HashSet<comment>();
        }
    
        public decimal ID_ACCOUNT { get; set; }
        public Nullable<decimal> ID_ACCOUNT_PERMISSIONS { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ACCOUNT_PERMISSION ACCOUNT_PERMISSION { get; set; }
        public virtual ICollection<comment> comments { get; set; }
    }
}
