//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public decimal ID_USER { get; set; }
        public decimal ID_RECIPE { get; set; }
        public string HEADER { get; set; }
        public string BODY { get; set; }
    
        public virtual account account { get; set; }
        public virtual RECIPE RECIPE { get; set; }
    }
}
