//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIPE()
        {
            this.comments = new HashSet<comment>();
            this.INGREDIENT_IN_RECIPE = new HashSet<INGREDIENT_IN_RECIPE>();
        }
    
        public decimal ID_RECIPE { get; set; }
        public string NAME { get; set; }
        public string IMAGE_FOLDER { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGREDIENT_IN_RECIPE> INGREDIENT_IN_RECIPE { get; set; }
    }
}
