//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeDBConnection : DbContext
    {
        public RecipeDBConnection()
            : base("name=RecipeDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<ACCOUNT_PERMISSION> ACCOUNT_PERMISSION { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENTs { get; set; }
        public virtual DbSet<INGREDIENT_IN_RECIPE> INGREDIENT_IN_RECIPE { get; set; }
        public virtual DbSet<MEASUREMENT_UNIT> MEASUREMENT_UNIT { get; set; }
        public virtual DbSet<RECIPE> RECIPEs { get; set; }
    }
}
