//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesGitHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<ACCOUNT_PERMISSION> ACCOUNT_PERMISSION { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<INGREDIENT> INGREDIENTs { get; set; }
        public DbSet<INGREDIENT_IN_RECIPE> INGREDIENT_IN_RECIPE { get; set; }
        public DbSet<MEASUREMENT_UNIT> MEASUREMENT_UNIT { get; set; }
        public DbSet<RECIPE> RECIPEs { get; set; }
    }
}
